#spring.application.name=springboot-kafka-tutorial
#spring.kafka.consumer.bootstrap-servers:localhost:9092.
#spring.kafka.consumer.group-id:myGroup
#spring.kafka.consumer.auto-offset-reset:earliest
#spring.kafka.consumer.key-deserializer:org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer:org.apache.kafka.common.serialization.StringDeserializer
#
#spring.kafka.producer.bootstrap-servers:localhost:9092
#spring.kafka.producer.key-serializer:org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer:org.apache.kafka.common.serialization.StringSerializer
#
#

spring:
  kafka:
    # Consumer Configuration
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-rest: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    # Producer Configuration
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer